

services:
  web:
    container_name: api
    build: .
    command: uvicorn --factory src.main:create_app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db/postgres
    
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
  
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"